/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testcheckJavaScriptFileMethod() {
        String stringResult =
                "Current errors:  \n" +
                "There is a missing ';' on Line: 3\n" +
                "There is a missing ';' on Line: 5\n" +
                "There is a missing ';' on Line: 8\n" +
                "There is a missing ';' on Line: 11\n" +
                "There is a missing ';' on Line: 13\n" +
                "There is a missing ';' on Line: 15\n" +
                "There is a missing ';' on Line: 17\n" +
                "There is a missing ';' on Line: 23\n" +
                "There is a missing ';' on Line: 26\n" +
                "There is a missing ';' on Line: 28\n" +
                "There is a missing ';' on Line: 30\n" +
                "There is a missing ';' on Line: 32\n" +
                "There is a missing ';' on Line: 34\n" +
                "There is a missing ';' on Line: 36\n" +
                "There is a missing ';' on Line: 38\n" +
                "There is a missing ';' on Line: 40\n" +
                "There is a missing ';' on Line: 41\n" +
                "There is a missing ';' on Line: 44\n" +
                "There is a missing ';' on Line: 48\n" +
                "There is a missing ';' on Line: 50\n" +
                "There is a missing ';' on Line: 51\n" +
                "There is a missing ';' on Line: 52\n" +
                "There is a missing ';' on Line: 54\n" +
                "There is a missing ';' on Line: 58\n" +
                "There is a missing ';' on Line: 59\n" +
                "There is a missing ';' on Line: 60\n" +
                "There is a missing ';' on Line: 61\n" +
                "There is a missing ';' on Line: 62\n" +
                "There is a missing ';' on Line: 64\n" +
                "There is a missing ';' on Line: 66\n" +
                "There is a missing ';' on Line: 68\n" +
                "There is a missing ';' on Line: 69\n" +
                "There is a missing ';' on Line: 70\n" +
                "There is a missing ';' on Line: 71\n" +
                "There is a missing ';' on Line: 72\n" +
                "There is a missing ';' on Line: 73\n" +
                "There is a missing ';' on Line: 74\n" +
                "There is a missing ';' on Line: 75\n" +
                "There is a missing ';' on Line: 76\n" +
                "There is a missing ';' on Line: 77\n" +
                "There is a missing ';' on Line: 78\n" +
                "There is a missing ';' on Line: 79\n" +
                "There is a missing ';' on Line: 80\n" +
                "There is a missing ';' on Line: 81\n" +
                "There is a missing ';' on Line: 82\n" +
                "There is a missing ';' on Line: 83\n" +
                "There is a missing ';' on Line: 84\n" +
                "There is a missing ';' on Line: 85\n" +
                "There is a missing ';' on Line: 86\n" +
                "There is a missing ';' on Line: 87\n" +
                "There is a missing ';' on Line: 88\n" +
                "There is a missing ';' on Line: 89\n" +
                "There is a missing ';' on Line: 90\n" +
                "There is a missing ';' on Line: 91\n" +
                "There is a missing ';' on Line: 92\n" +
                "There is a missing ';' on Line: 93\n" +
                "There is a missing ';' on Line: 94\n" +
                "There is a missing ';' on Line: 95\n" +
                "There is a missing ';' on Line: 96\n" +
                "There is a missing ';' on Line: 97\n" +
                "There is a missing ';' on Line: 98\n" +
                "There is a missing ';' on Line: 99\n" +
                "There is a missing ';' on Line: 100\n" +
                "There is a missing ';' on Line: 101\n" +
                "There is a missing ';' on Line: 102\n";
        Path testFile = Paths.get("src/main/resources/gates.js");

        assertEquals(stringResult, App.checkJavaScriptFile(testFile));
    }
}
