/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

    }

    public static String checkJavaScriptFile(Path filePath){

        Scanner fileScanner;
        String message = "Current errors:  \n";
        try{

            fileScanner = new Scanner(new File(filePath.toUri()));
            int currentLineNumber = 1;

            while( fileScanner.hasNextLine()){
                String currentLine = fileScanner.nextLine();
                if(!currentLine.endsWith(";") && !currentLine.endsWith("}") && !currentLine.endsWith("{") && !currentLine.contains("if") && !currentLine.contains("else") ) {
                    message += "There is a missing ';' on Line: " + currentLineNumber + "\n";
                }
                currentLineNumber ++;
            }

        }catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return message;
    }
}
