/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import com.sun.org.apache.xpath.internal.operations.String;
import org.junit.Test;

import java.util.regex.Pattern;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollMethod() {
        int[] expectedLength = new int[4];

        assertEquals(expectedLength.length, Library.roll(4).length);
    }

    @Test public void testElementsInRollMethod() {
        boolean testResult = false;
        int[] testData = Library.roll(5);

        for ( int number : testData) {
            if (number >= 0 && number <= 6) {
                testResult = true;
            } else {
                testResult = false;
                break;
            }
        }

        assertTrue("It is true!", testResult);

    }

    @Test public void testContainsDuplicatesMethod() {
        int[] testArray = {1,2,3,4,5,6,7,7,8,9};
        int[] secTestArray = {1,2,3,4,5,6,7,8,9};

        assertEquals(true, Library.containsDuplicates(testArray));
        assertEquals(false, Library.containsDuplicates(secTestArray));
    }

    @Test public void testCalculatingAveragesMethod() {
        int[] testArray = {1,2,3,4,5,6,7,8,9,10};

        assertEquals(5, Library.calculatingAverages(testArray));
    }

    @Test public void testArrayWithTheLowestAverageMethod() {
        int[][] arrayOfTestData = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] returnValue = new int[] {55, 54, 60, 53, 59, 57, 61};

        assertArrayEquals(returnValue, Library.arrayWithTheLowestAverage(arrayOfTestData));
    }
}
