/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import org.junit.Test;

import java.util.*;


import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollMethod() {
        int[] expectedLength = new int[4];

        assertEquals(expectedLength.length, Library.roll(4).length);
    }

    @Test public void testElementsInRollMethod() {
        boolean testResult = false;
        int[] testData = Library.roll(5);
        for ( int number : testData) {
            if (number > 0 && number < 7) {
                testResult = true;
            } else {
                testResult = false;
                break;
            }
        }

        assertTrue("It is true!", testResult);

    }

    @Test public void testContainsDuplicatesMethod() {
        int[] testArray = {1,2,3,4,5,6,7,7,8,9};
        int[] secTestArray = {1,2,3,4,5,6,7,8,9};

        assertEquals(true, Library.containsDuplicates(testArray));
        assertEquals(false, Library.containsDuplicates(secTestArray));
    }

    @Test public void testCalculatingAveragesMethod() {
        int[] testArray = {1,2,3,4,5,6,7,8,9,10};
        double answer = 5.5;
        assertEquals(answer, Library.calculatingAverages(testArray), .1);
    }

    @Test public void testArrayWithTheLowestAverageMethod() {
        int[][] arrayOfTestData = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] returnValue = new int[] {55, 54, 60, 53, 59, 57, 61};

        assertArrayEquals(returnValue, Library.arrayWithTheLowestAverage(arrayOfTestData));
    }

    @Test public void testAnalyzingWeatherDataMethod() {
        int[][] testArr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals("High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n", Library.analyzingWeatherData(testArr));
    }

    @Test public void testTallyMethod() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");


        assertEquals("Bush", Library.tally(votes));
    }


}
